version: "3"

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  hello_docker:
    image: bestofsong/hello_docker:0.0.1
    ports:
      - "80:80"

    environment:
      - DB_PORT=3306
      - DB_IP=mysql
      - DB_NAME=main
      - DB_USER=app
      - DB_PW=12345678
    depends_on:
      - mysql

volumes:
  mysql:
    external: true
